### ISSUE TITLE
Amiibo no longer works

### ISSUE THREAD

**Issue by DogmaBomb** [flipperdevices/flipperzero-firmware#1177] opened 2022-04-28 07:20 UTC
**Describe the bug**
Before updating to 0.56.1 the amiibo were loading just fine to my switch, 
now with the new update to 0.56.1 the Amiibos will not load in after 
multiple tries.

**To Reproduce**
Scanned NFC with Zelda BOTW
Worked before
Doesn't work with firmware 0.56.1

**Expected behavior**
Changes made to official firmware

**Logs**
None

**Target**
Nintendo Switch

**Additional context**
Will attempt to run previous firmware to ensure amiibos still work

**Comment by gornekich** [comment] 2022-04-28 11:10
Fix in https://github.com/flipperdevices/flipperzero-firmware/pull/1179
Soon will be in release

**Comment by jlaughter** [comment] 2022-04-28 13:33
Duplicate of #1169.  You can [downgrade to 55.1](https://update.flipperzero.one/builds/firmware/0.55.1/) as a workaround.

**Comment by skotopes** [comment] 2022-04-28 16:11
Fixed in dev, will be in release 0.57

**Closed as completed** 2022-04-28 16:10 UTC
Labels: Bug
