### ISSUE TITLE
Memory card encryption

### ISSUE THREAD

**Issue by krisss117** [flipperdevices/flipperzero-firmware#3169] opened 2023-10-27 19:03 UTC
### Description of the feature you're suggesting.

Flipper Zero contains a lot of critical data, such as MiFare Classic access cards, SUB-GHZ codes for gate access, and more. These are quite sensitive data, and in case the device is lost, they are easily accessible to anyone who finds it.

Implementing memory card encryption will secure the data we have collected with Flipper.

### Anything else?

I imagine that after starting Flipper, we would need to enter a key to unlock the memory card. It would be ideal if Flipper could automatically unlock the memory card, for example, when the phone is within Bluetooth range - that way, we wouldn't have to remember the password and enter it every time it's restarted.

**Comment by hedger** [comment] 2023-10-29 18:31
Duplicate of #1201

**Closed as not planned by hedger** 2023-10-29 18:31 UTC
Labels: Feature Request
