### ISSUE TITLE
Pre-recorded "READ" files stopped working.

### ISSUE THREAD

**Issue by GR-noob** [flipperdevices/flipperzero-firmware#2359] opened 2023-02-04 20:29 UTC
### Describe the bug.

I was at (i think) 0.74.0 update and i updated to 0.76.0. I found that my flipper the sub files for 2 gates, that i READ and saved stopped working but the READ RAW saved files still worked without problem. I re-record the 2 remotes in READ saved file again didn't work at READ RAW worked ok. I downgraded my flipper to 0.74.2 and started work again ok with the pre-recorded just RAED files started working again.

### Reproduction

just that pre-recorded just READ saved files didn't emulate anymore at the new update.

**Comment by Skorpionm** [comment] 2023-02-05 21:38
attach non-working files saved in read

**Comment by GR-noob** [comment] 2023-02-06 17:00
I can share only the 1 file sorry

https://drive.google.com/file/d/1xMjVtweQwPcVh0RCAEbv6NuAHuXsV9IZ/view?usp=sharing

**Comment by skotopes** [comment] 2023-03-03 15:14
Issue was fixed in #2443 please check and let us know if it still persist

**Comment by GR-noob** [comment] 2023-03-14 18:57
Hello. I updated my flipper to 0.79.1 and kinda again READ and saved stopped working. I re-READ the remote and this time works ok is just the old saved don't work anymore. Tomorrow i will test the file above ( commented on Feb 6 ) if it works for the other door or is just my door don't work. I will post again tomorrow.
The diference of the saved file of the old:
![old](https://user-images.githubusercontent.com/27872693/225108994-118c2def-d9a7-42e4-9c02-32b7be4fecb6.png)
And new:
![new](https://user-images.githubusercontent.com/27872693/225109014-26c8b88b-d73e-4001-8152-b2bce47b254a.png)

**Comment by skotopes** [comment] 2023-03-15 03:18
Can you provide us raw signal for analysis?

**Comment by GR-noob** [comment] 2023-03-18 16:51
i will upload 3 files. Is from the same door where i can provide without problem. OLD is the file who don't work anymore. NEW is the new READ save who works now and the OLD RAW is the RAW save from the old firmware who also works.

https://drive.google.com/file/d/1fH5002u3gCRRcuRSrjeoCa0_YlVNy49S/view?usp=sharing
https://drive.google.com/file/d/1QN1ykV_9IJBgtHFgjcTidmAOXbMJNSB4/view?usp=sharing
https://drive.google.com/file/d/1B9vONsHPLMojed463_JQpDdfPHiDbm3Q/view?usp=sharing

**Comment by Ethanol0001** [comment] 2023-03-28 20:56
@skotopes you think this might have been caused by the removal of the furi value mutex in the last update?

**Comment by Ethanol0001** [comment] 2023-03-28 20:58
wondering if the old files cant be recognized if its saving with the new system and is unable to read files still containing stuff that uses the furi value mutex

**Comment by GR-noob** [comment] 2023-04-12 20:18
Version 0.81.1 and still can't sent old files. I am the only one with this problem ?? I am so stupid i do something wrong ?? I am just curious if that cause problems with files i downloaded for different devises like some selling fans.

**Comment by skotopes** [comment] 2023-04-13 04:13
> Version 0.81.1 and still can't sent old files. I am the only one with this problem ?? I am so stupid i do something wrong ?? I am just curious if that cause problems with files i downloaded for different devises like some selling fans.

What exactly flipper tells you when you trying to send?

**Comment by skotopes** [comment] 2023-04-13 04:39
@Skorpionm regarding TE to Holtek_HT12X, is default value(TE is not set) same as old one?

**Comment by GR-noob** [comment] 2023-04-13 05:25
> > Version 0.81.1 and still can't sent old files. I am the only one with this problem ?? I am so stupid i do something wrong ?? I am just curious if that cause problems with files i downloaded for different devises like some selling fans.
> 
> What exactly flipper tells you when you trying to send?

I click SENT the led flashes as always but door don't open and nothing show at the screen except the 2 lines KEY and YEK. Do i downgrade again back to  0.74.2 to see if file still works ?? Because that was the last firmware it worked

**Comment by Skorpionm** [comment] 2023-04-13 06:20
after firmware 0.74.2, the CAME protocol timings were changed and a new Holtek protocol was added. The system was not correctly recognized in your old saved files, but with the old CAME protocol settings, your receiver could somehow still recognize the signal, now it simply does not recognize it, since the timings in CAME have been corrected to be more accurate. You just need to accept the data from the original remote control of your system again in the new firmware, save it and use it

**Comment by Skorpionm** [comment] 2023-04-13 06:34
![image](https://user-images.githubusercontent.com/85568270/231673812-90be9b3f-9633-4243-a8e8-53defa3e57d2.png)
all your files are playable and working

**Closed as completed** 2023-04-13 06:56 UTC
Labels: Sub-GHz, Bug
