### ISSUE TITLE
Sub Ghz cannot parse file/Transmission Blocked

### ISSUE THREAD

**Issue by kritonpc** [flipperdevices/flipperzero-firmware#2345] opened 2023-01-29 19:12 UTC
### Describe the bug.

Although I've never had any issues with sub ghz I encountered an issue some time in the past and again today.
I recorded a remote that works at 433.92 and when i pressed send directly after recording it and it was recognized, it showed me a transmission error saying that the specific frequency is not supported (although it is 433.92, which is supported in my country). I saved it and tried sending it and when selecting the file it shows the error "Cannot parse file". I tried it several times but it doesn't work. When saving it RAW of course it worked, but the rest seems odd. Any idea what can be wrong? I tried it on both OFW and on a CFW with unlocked transmission and it persists. Here are the .sub files of the 2 remotes as they were saved on flipper:

```
Filetype: Flipper SubGhz Key File
Version: 1
Frequency: 433920000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: CAME
Bit: 32
Key: 00 00 00 00 66 CF 63 02
```
and
```
Filetype: Flipper SubGhz Key File
Version: 1
Frequency: 433889000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: CAME
Bit: 32
Key: 00 00 00 00 F7 46 88 12

```

### Reproduction

1. Record the remote 
2. Press send directly after recording it 
3. It shows a transmission error saying that the specific frequency is not supported

and 
1. Save the remote as a .sub file
2. Select it
3. It shows the error "Cannot parse file"

**Comment by Skorpionm** [comment] 2023-02-02 15:05
it's not a bug, came.  The protocol only supports 12 and 24 bits.  instead of the other varieties of this protocol is not the same.  send raw.  recording several long presses on each button on the remote control.  and attach a photo and the name of your system, I will add it

**Comment by kritonpc** [comment] 2023-02-03 16:06
This is for the first one
```Filetype: Flipper SubGhz RAW File
Version: 1
Frequency: 433920000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: RAW
RAW_Data: -1154 163 -296 165 -990 99 -132 365 -198 199 -364 925 -432 99 865 51303 -14132 65 -2054 65 -100 393 -860 489 -100 163 -562 789 -98 165 -64 37125 -13712 197 -132 97 -1858 895 -332 101 -398 993 -164 267 -200 232083 -6698 65 -5076 67 -364 331 -168 231 -230 395 -990 495 -766 165 -66 859 -660 885 -100 327 -230 31739 -664 273 -386 583 -682 277 -384 559 -682 279 -388 553 -698 275 -386 557 -376 603 -356 589 -386 587 -358 579 -380 585 -372 575 -684 277 -690 307 -660 279 -360 591 -682 279 -356 623 -664 275 -664 303 -680 255 -696 283 -660 289 -680 277 -356 591 -374 587 -684 275 -686 273 -660 311 -358 593 -11474 317 -362 593 -352 607 -656 289 -682 313 -630 305 -652 311 -660 311 -324 603 -678 283 -362 597 -320 637 -668 291 -328 637 -642 319 -632 295 -672 315 -340 607 -344 631 -644 315 -662 279 -662 315 -310 635 -668 301 -660 283 -344 601 -672 283 -338 633 -668 293 -660 283 -336 631 -672 289 -328 645 -11472 305 -350 601 -644 319 -666 289 -344 615 -346 623 -644 311 -660 275 -356 605 -676 283 -654 291 -340 647 -314 619 -672 311 -630 305 -648 317 -662 319 -318 621 -672 301 -662 283 -342 601 -376 603 -320 629 -672 289 -658 283 -338 631 -354 619 -328 615 -346 623 -344 609 -326 609 -656 291 -340 647 -11466 329 -638 309 -662 315 -324 631 -648 319 -326 589 -658 317 -634 331 -312 645 -326 607 -658 291 -666 315 -636 329 -642 313 -626 343 -622 309 -662 313 -662 309 -626 319 -362 595 -644 319 -326 625 -324 651 -622 321 -658 311 -628 307 -356 605 -646 317 -656 309 -304 647 -324 619 -652 309 -308 653 -11450 343 -656 323 -326 595 -680 285 -668 287 -344 615 -654 305 -652 311 -630 345 -322 607 -324 649 -322 623 -652 317 -638 291 -670 311 -628 307 -356 639 -642 321 -326 625 -646 309 -630 317 -364 595 -320 631 -658 289 -350 613 -670 313 -620 345 -304 643 -626 321 -308 653 -314 621 -672 313 -626 307 -11478 317 -362 589 -674 313 -628 307 -650 315 -660 283 -362 589 -360 615 -660 299 -648 299 -658 321 -306 633 -644 315 -306 635 -344 635 -322 633 -318 663 -314 621 -672 313 -628 307 -652 311 -660 311 -622 297 -336 633 -346 631 -308 637 -318 631 -348 597 -672 283 -660 319 -662 299 -346 611 -646 313 -11446 353 -628 307 -652 311 -660 311 -326 603 -322 653 -658 287 -344 621 -350 619 -310 613 -652 345 -324 629 -296 635 -648 321 -634 313 -326 625 -672 313 -658 315 -624 297 -658 319 -326 623 -326 649 -314 623 -338 627 -656 303
RAW_Data: -650 311 -308 635 -356 591 -352 609 -352 621 -332 615 -334 633 -320 633 -11478 323 -630 331 -640 285 -336 637 -668 299 -644 283 -336 635 -670 289 -660 283 -338 631 -672 289 -660 311 -626 311 -356 595 -346 625 -648 311 -308 667 -658 289 -672 281 -338 629 -658 289 -678 279 -666 301 -648 311 -308 637 -656 291 -338 649 -630 297 -674 313 -626 307 -656 309 -664 311 -626 297 -11484 321 -670 289 -328 635 -642 319 -338 601 -352 599 -354 605 -346 627 -346 601 -318 635 -346 631 -310 637 -320 631 -670 291 -328 615 -332 635 -656 323 -638 313 -336 629 -658 289 -346 615 -346 623 -646 313 -310 633 -656 291 -662 311 -660 321 -328 595 -318 635 -354 619 -630 315 -362 589 -338 647 -11438 335 -350 605 -646 317 -328 633 -644 321 -306 631 -350 599 -648 317 -662 301 -646 315 -660 275 -662 315 -662 309 -622 319 -326 635 -642 319 -326 625 -360 617 -656 291 -332 615 -650 343 -324 627 -648 311 -624 309 -342 605 -356 623 -320 611 -660 321 -650 283 -336 633 -658 289 -676 281 -660 319 -11472 309 -658 319 -326 627 -648 321 -632 289 -346 617 -346 623 -312 647 -326 607 -356 625 -318 611 -352 619 -666 315 -628 303 -352 607 -326 645 -648 317 -652 283 -338 631 -658 289 -678 281 -338 629 -658 289 -348 615 -654 307 -652 311 -662 311 -324 605 -644 319 -326 635 -642 319 -326 625 -322 649 -11450 319 -336 645 -650 311 -626 297 -660 319 -306 633 -350 599 -678 319 -326 623 -626 315 -636 329 -312 645 -646 315 -620 345 -302 645 -648 287 -676 313 -308 635 -646 319 -668 283 -660 321 -326 627 -646 321 -632 289 -644 349 -326 589 -340 647 -296 637 -656 291 -338 645 -624 321 -660 311 -310 635 -11480 313 -658 315 -652 285 -660 319 -326 619 -630 313 -668 301 -646 285 -660 319 -326 623 -654 317 -326 621 -334 615 -173470 265 -502 131 -166 593 -164 263 -950 331 -98 299 -766 825 -298 163 -496 1283 -130 295 -12142 397 -1016 465 -200 197 -916 331 -1350 425 -100 327 -924 961 -100 165 -100 133 -400 1091 -66 197 -98 20515 -10968 97 -1026 229 -164 97 -130 291 -764 399 -232 297 -1064 97 -134 459 -296 165 -528 887 -268 1659 -100 299 -100 8081 -10714 65 -1654 99 -3016 165 -794 65 -532 799 -68 133 -696 1191 -66 399 -200 14585 -7520 97 -3066 97 -64 293 -1654 197 -100 991 -392 795 -66 299 -264
```

This is for the second
```
Filetype: Flipper SubGhz RAW File
Version: 1
Frequency: 433889000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: RAW
RAW_Data: 23879 -66 10887 -16830 199 -200 65 -232 65 -894 927 -766 331 -364 697 -68 3815 -132 40451 -100 14373 -132 21721 -66 3613 -100 4577 -100 335 -66 4783 -66 2291 -132 2987 -132 16599 -16668 65 -764 131 -132 99 -566 65 -232 593 -266 299 -498 165 -166 1493 -132 13829 -66 3453 -132 2325 -17520 263 -134 99 -234 299 -98 697 -1020 857 -66 131 -134 235 -200 65 -98 2707 -66 1599 -102 3857 -66 1885 -66 1031 -100 1793 -100 5639 -66 1663 -100 5289 -98 1915 -66 1559 -98 5407 -166 1261 -66 3329 -102 3733 -66 3235 -130 1675 -100 3823 -100 4655 -66 4985 -132 19641 -130 229 -66 4607 -100 9971 -16444 63 -1558 65 -100 231 -1030 363 -828 1493 -68 1573 -132 295 -98 1237 -132 301 -102 3659 -132 4759 -132 5761 -66 3591 -130 1719 -98 6435 -64 653 -66 3463 -100 4671 -134 3019 -68 3259 -66 1515 -100 3599 -66 1773 -66 1357 -100 1927 -68 529 -66 2345 -68 1725 -66 997 -68 533 -66 23779 -66 1601 -98 3599 -98 3249 -66 5269 -66 431 -66 4165 -66 295 -66 5033 -100 1861 -98 19865 -134 10471 -66 1763 -66 3075 -132 23591 -64 1119 -66 3551 -66 529 -134 1449 -132 1511 -100 1089 -68 3815 -100 2811 -100 1623 -164 1447 -134 1773 -16542 733 -100 367 -132 361 -66 2885 -98 1181 -66 227 -66 21323 -98 1649 -66 1591 -66 267 -134 1707 -66 1779 -100 3777 -98 1975 -98 10521 -100 3885 -64 7745 -17836 463 -130 131 -362 327 -100 231 -998 933 -694 133 -66 2917 -100 2155 -134 2999 -66 19745 -68 5539 -68 1259 -66 1759 -66 2121 -68 3183 -68 4073 -68 1595 -166 3323 -66 3757 -66 1655 -66 2091 -98 1221 -66 12353 -134 5263 -100 1751 -98 23127 -98 67 -66 10183 -354 593 -668 275 -692 271 -680 263 -376 601 -694 263 -374 607 -354 599 -664 291 -668 285 -342 629 -340 635 -346 619 -650 309 -354 599 -646 315 -352 591 -366 611 -344 623 -346 605 -680 281 -354 597 -684 315 -632 295 -672 309 -336 609 -352 625 -654 281 -346 615 -386 587 -362 613 -656 299 -11506 345 -622 317 -664 309 -624 355 -628 291 -340 643 -624 331 -650 309 -660 313 -324 629 -644 315 -324 631 -324 647 -320 625 -658 317 -632 329 -314 645 -644 317 -324 635 -320 633 -350 621 -634 351 -322 623 -312 647 -326 637 -322 623 -326 647 -312 655 -646 311 -308 633 -356 627 -646 309 -310 645 -11518 317 -648 313 -628 321 -666 287 -348 623 -654 301 -354 611 -324 643 -658 289 -348 621 -654 303 -356 607 -646 351 -628 293 -338 641 -314 655 -310 651 -646 311 -324 639 -318 625 -636 321 -334 647 -646 313 -652 309 -304 649 -320 655 -298 649 -348 619 -314
RAW_Data: 647 -646 313 -652 293 -338 643 -314 653 -11502 349 -272 665 -626 321 -638 351 -322 625 -646 313 -308 631 -356 629 -290 669 -634 339 -622 347 -270 669 -626 321 -642 349 -324 623 -310 663 -616 341 -324 607 -322 649 -320 655 -630 317 -322 657 -644 313 -626 341 -624 347 -620 315 -324 631 -324 645 -320 653 -626 311 -662 321 -326 625 -650 309 -11504 353 -596 329 -646 315 -630 341 -310 645 -658 287 -350 615 -652 341 -324 627 -294 667 -646 289 -348 623 -654 303 -656 309 -308 671 -626 319 -642 351 -626 301 -352 611 -324 645 -658 287 -348 615 -652 341 -324 607 -644 353 -292 633 -322 671 -314 621 -336 617 -650 341 -648 287 -666 279 -664 313 -11518 321 -636 311 -662 317 -322 627 -652 315 -662 301 -646 309 -338 607 -354 623 -326 645 -658 297 -646 309 -338 639 -656 289 -642 313 -342 623 -654 289 -684 285 -340 627 -654 321 -326 621 -344 625 -348 607 -648 313 -660 293 -342 643 -346 617 -646 309 -660 309 -624 343 -302 647 -318 623 -658 313 -11506 351 -308 635 -648 293 -340 643 -652 289 -668 311 -660 309 -622 343 -626 313 -660 293 -668 317 -632 327 -344 609 -646 313 -658 309 -658 319 -322 629 -322 643 -312 619 -674 313 -306 635 -354 627 -322 643 -312 621 -340 647 -648 311 -322 625 -644 313 -640 321 -660 315 -310 629 -670 299 -350 603 -11532 321 -636 323 -644 311 -308 633 -354 625 -324 645 -314 621 -342 647 -650 309 -322 635 -650 309 -632 351 -636 289 -334 647 -326 641 -310 635 -348 603 -646 317 -342 633 -648 285 -668 315 -664 297 -644 317 -666 319 -322 623 -334 613 -332 633 -646 323 -312 645 -332 633 -648 293 -340 643 -334 633 -11484 319 -314 655 -344 621 -646 309 -660 311 -320 633 -322 631 -342 633 -346 607 -646 313 -358 597 -354 605 -348 621 -338 611 -350 611 -352 625 -654 317 -318 623 -672 311 -306 635 -354 625 -650 279 -666 313 -658 293 -668 311 -634 315 -660 291 -342 645 -656 297 -350 621 -648 309 -322 633 -646 317 -11514 319 -652 311 -306 633 -656 293 -666 313 -310 653 -352 621 -628 315 -358 623 -312 647 -326 639 -320 625 -324 647 -346 619 -310 661 -616 341 -622 345 -624 313 -660 293 -340 641 -312 655 -644 311 -626 341 -322 625 -646 313 -324 633 -646 317 -358 621 -626 315 -356 621 -646 311 -624 343 -624 343 -11476 353 -328 629 -320 641 -622 319 -664 311 -306 635 -656 323 -310 647 -656 301 -650 309 -338 637 -320 625 -328 645 -348 619 -646 311 -306 633 -354 625 -324 645 -654 289 -332 647 -324
RAW_Data: 639 -636 325 -310 645 -646 313 -322 635 -644 319 -662 287 -348 615 -652 339 -322 625 -324 641 -320 623 -326 647 -11496 343 -620 317 -342 639 -652 289 -666 311 -306 635 -654 323 -638 313 -664 319 -320 627 -324 645 -346 619 -308 647 -324 643 -656 289 -642 313 -356 623 -646 309 -660 309 -322 635 -320 627 -656 321 -326 611 -330 637 -352 625 -326 645 -652 289 -332 645 -648 309 -322 633 -324 647 -660 297 -346 603 -11506 359 -632 289 -350 619 -654 303 -352 623 -324 641 -654 289 -642 313 -356 625 -346 623 -296 639 -352 625 -654 315 -320 623 -672 313 -624 339 -620 345 -622 313 -660 293 -340 643 -654 289 -666 311 -306 635 -354 627 -650 319 -318 623 -670 311 -320 627 -348 621 -326 607 -352 625 -652 311 -668 317 -11482 321 -340 613 -344 623 -646 309 -338 607 -688 287 -348 619 -344 623 -346 607 -646 313 -358 595 -354 603 -670 301 -652 307 -338 643 -318 625 -656 313 -342 619 -656 289 -352 613 -684 305 -320 623 -646 311 -658 293 -670 313 -664 297 -646 307 -336 609 -350 625 -654 313 -668 281 -354 627 -650 279 -11528 353 -618 291 -342 645 -656 299 -350 607 -644 353 -322 597 -648 353 -628 289 -352 613 -344 627 -350 607 -644 353 -626 293 -340 645 -624 331 -348 609 -646 315 -660 293 -340 641 -624 331 -348 609 -644 351 -326 595 -322 637 -350 621 -668 313 -306 633 -352 627 -648 279 -666 315 -658 293 -342 641 -11514 323 -640 313 -306 635 -354 627 -650 279 -664 313 -660 293 -342 641 -656 297 -348 607 -324 647 -656 287 -352 613 -650 339 -622 343 -302 643 -318 623 -658 313 -664 319 -624 323 -312 643 -346 621 -346 607 -646 315 -358 595 -354 603 -656 321 -662 311 -626 341 -622 343 -302 645 -320 623 -330 645 -11500 341 -326 631 -322 643 -314 621 -674 313 -626 339 -618 319 -666 317 -632 325 -642 311 -336 605 -656 321 -314 645 -654 301 -652 309 -658 313 -358 591 -322 649 -656 289 -682 281 -342 625 -344 635 -320 633 -322 627 -350 621 -668 313 -626 301 -654 309 -658 313 -658 293 -342 641 -626 327 -346 609 -11510 321 -634 321 -310 643 -318 635 -354 625 -324 645 -314 653 -310 647 -648 311 -322 635 -320 627 -666 291 -668 311 -306 633 -354 625 -324 645 -314 653 -644 313 -626 341 -622 345 -622 313 -662 293 -666 319 -632 327 -308 647 -324 643 -644 289 -650 347 -322 625 -312 645 -646 313 -324 627 -322 649 -11512 319 -658 313 -624 339 -620 329 -632 317 -342 635 -318 635 -326 643 -346 587 -344 623 -652 339 -110866 131 -2888
RAW_Data: 199 -132 329 -794 1291 -102 8521 -12410 67 -3444 131 -1228 65 -200 431 -330 67 -198 65 -266 497 -64 629 -66 131 -398 61581 -17170 65 -526 97 -986 787 -958 895 -166 1401 -66 25975 -66 2799 -66 1895 -132 4815 -66 21743 -68 3429 -68 3445 -100 14479 -100 23351 -128 881 -132 23145 -100 1865 -132 2041 -66 1349 -98 623 -100 1557 -66 10817 -100 5383 -134 1497 -98 3125 -66 3349 -134 365 -134 2897 -98 20625 -17492 165 -198 431 -100 65 -398 165 -98 99 -100 599 -856 623 -100 389 -130 325 -100 11797 -98 3989 -68 12123 -100 10501 -102 199 -134 21763 -66 1341 -66 12767 -100 8047 -17524 97 -294 97 -132 923 -900 861 -66 497 -66 16061 -66 2989 -98 651 -66 6905 -100 3613
```

This is all I have, as they are from friends and family. I have to get extra info from them. What else do you need?

**Comment by Skorpionm** [comment] 2023-02-05 21:41
still need the name of the system and a photo of the remote control

**Comment by kritonpc** [comment] 2023-02-06 15:41
For the first one, it seems to be a Proteco Mover 5 or something. I couldn't find information on it, but google lens seemed to do the job.
![IMG_20230206_173635_415](https://user-images.githubusercontent.com/693201/217015424-a57e676f-cf0b-44b8-bfe1-405a62ed4ef1.jpg)
This is the motor and it seems to be this https://www.adg.ie/Automation/mover_mag--Proteco-Mover-Sliding-Gate-Motor-Kit-

The remote is this:
![IMG_20230206_173127_672](https://user-images.githubusercontent.com/693201/217016063-c45953d3-b811-461a-9d46-04d87e86d15d.jpg)
![IMG_20230206_173129_675](https://user-images.githubusercontent.com/693201/217016095-e2a812c4-2f40-40eb-a640-0621ac9dc688.jpg)

I'll try to find the second one ASAP. If you need additional information let me know

**Comment by skotopes** [comment] 2023-03-03 15:14
Issue was fixed in #2443 please check and let us know if it still persist

**Closed as completed by skotopes** 2023-03-03 15:14 UTC
Labels: Sub-GHz, Bug

**Comment by kritonpc** [comment] 2023-03-10 13:09
It still doesn't allow me to transmit it. I just get a more specific error.

**Comment by skotopes** [comment] 2023-03-10 14:35
@kritonpc what exactly it saying?

**Comment by kritonpc** [comment] 2023-03-10 14:46
"Error in protocol parameters description"

**Comment by Skorpionm** [comment] 2023-03-10 18:24
now you can include BinRaw in the config, and accept this console again. should persist and correctly play unsupported protocols

**Comment by kritonpc** [comment] 2023-03-10 23:39
@Skorpionm What do you mean? What should I change on the saved file? What actions should i follow?

**Comment by Skorpionm** [comment] 2023-03-11 05:54
no need to do anything with the saved file.  open read -> config -> bin raw .  return to read and accept the signal from the remote control again, you will have a binraw format signal.  save this and use it, it should repeat the signal from your key fob in strength.  also works, transmits while the transmit button is pressed

**Comment by dkorunic** [comment] 2024-01-30 09:28
The system above is Proteco MOVER, I can confirm. Can we get a protocol parser for this @Skorpionm please? It's quite common 230V gate mover/opener system in EU and produced in Italy. I'm able to send a few raw files if needed.

**Comment by KitengeibrahPro** [comment] 2025-04-07 06:38
same error BIN RAW TRANSMISSION IS BLOCKED 

![Image](https://github.com/user-attachments/assets/352652f7-965a-4edd-b9d4-5fe4d6399b8b)
![Image](https://github.com/user-attachments/assets/96c80830-4092-4d5b-af9f-bbb3f41a5ad0)

**Comment by Skorpionm** [comment] 2025-04-07 08:20
install the official firmware, and try to save binraw again and send. I can't answer for other firmware and files generated by unknown people

**Comment by KitengeibrahPro** [comment] 2025-04-07 12:35
> install the official firmware, and try to save binraw again and send. I can't answer for other firmware and files generated by unknown people

Issue resolved from the official firmware. Thank you so much!
