### ISSUE TITLE
Bug in level 2 animation system.

### ISSUE THREAD

**Issue by Danucosukosuko** [flipperdevices/flipperzero-firmware#3213] opened 2023-11-12 13:51 UTC
### Describe the bug.

My flipper is in the level 2 and shows the animations of level 1

### Reproduction

Automatic

### Anything else?

Correct plz

**Comment by hedger** [comment] 2023-11-12 15:22
Does it show animations from level 1 only? Or both 1&2?

**Comment by Danucosukosuko** [comment] 2023-11-12 21:50
Only from the Level 1

**Comment by Danucosukosuko** [comment] 2023-11-12 21:54
I tested in 0.90.1 FW and nothing, but in 0.94.1 shows the L1 Animations

**Comment by Danucosukosuko** [comment] 2023-11-12 22:02
I tested in 0.90.1 FW and shows both Animations, L1 & L2, but in 0.94.1 shows the L1 Animations

**Comment by doomwastaken** [comment] 2023-11-13 10:11
Unable to reproduce, tested on lvl2, lvl3 devices in Ok / Angry mood

**Comment by Danucosukosuko** [comment] 2023-11-13 13:00
This morning I finally got a Lvl2 one. I think should show more of lvl2 than 1

**Comment by doomwastaken** [comment] 2023-11-14 08:47
You can cycle animations by turning device on and off, that way you can be sure that they are working correctly. As for animations, here is the list
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/72250702/f69f8246-1148-46fc-a3a5-e9b961ed42d6)


I will close this issue, reopen it if issue persists

**Closed as completed by doomwastaken** 2023-11-14 08:47 UTC
Labels: Bug, UI, Core+Services

**Comment by Danucosukosuko** [comment] 2023-11-14 18:16
Ok
