### ISSUE TITLE
NFC - Missing function?

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3258] opened 2023-12-02 23:44 UTC
### Describe the bug.

In NFC/Extra actions menu is item "Mifare Classic Keys". On press OK, this item does nothing, only returns to NFC menu.

### Reproduction

Open menu - NFC - Extra Actions - click on Mifare Classic Keys

**Comment by skotopes** [comment] 2023-12-04 06:57
Check your SD card: ensure that NFC app assets are not damaged.
Format SD Card and reinstall firmware.

**Comment by skotopes** [comment] 2023-12-04 06:58
@gornekich I think we should show some error message when we can't open file

**Comment by Tomi2965** [comment] 2023-12-04 10:02
> Check your SD card: ensure that NFC app assets are not damaged. Format SD Card and reinstall firmware.

@skotopes  Checked - problem not fixed. I was try:
- replace card with a new one, then reformat, copy old data back, then reinstall 0.95.0,
- update from 0.95.0 to RC 0.96.0,
- reinstall RC 0.96.0,
- factory reset, installed RC 0.96.0 (just clean install without any data on int/ext mem),
- factory reset, installed 0.95.0 (just clean install without any data on int/ext mem),
- put my FZ to previous state (with new SD card, old data from int/ext mem), reinstall FW.

I was try to enter NFC-Extra Act.-Mifare Classic Keys after each step. Still same result. Any suggestions? Can you please verify this on another FZ? Thanks a lot.

**Comment by FearnessBG** [comment] 2023-12-04 10:43
When connecting to qFlipper, can you download the file and open it with text editor? It must be in the main directory in folder nfc, then in assets folder. It will end in .nfc, you can open it with text editor. Does it open at all?

**Comment by Tomi2965** [comment] 2023-12-04 11:07
Verified files:
/ext/nfc/assets/aid.nfc (152 lines)
/ext/nfc/assets/country_code.nfc (252 lines)
/ext/nfc/assets/currency_code.nfc (171 lines)
/ext/nfc/assets/mf_classic_dict.nfc (1314 lines)
/ext/nfc/iPassan.nfc (one of my saved keys, 77 lines)

Every file is openable, uncorrupted.

**Comment by FearnessBG** [comment] 2023-12-04 11:19
Can you open it on the FZ with the browser to read it?

**Comment by FearnessBG** [comment] 2023-12-04 11:20
And did you make any nfc nesting ? Because i was not able to open it from where you want till made first reading with MF1 s50 4 mb

**Comment by FearnessBG** [comment] 2023-12-04 11:26
You don't have the mf_classic_dict_user.nfc .That is why i am asking?

**Comment by gornekich** [comment] 2023-12-04 11:28
Reproduced this issue, will be fixed soon

**Comment by Tomi2965** [comment] 2023-12-04 11:31
> Can you open it on the FZ with the browser to read it?

Which file u mean? Browser - just in "Saved" submenu?



> And did you make any nfc nesting ? Because i was not able to open it from where you want till made first reading with MF1 s50 4 mb

Yep, I have five saved NFC's in /ext/nfc folder



> You don't have the mf_classic_dict_user.nfc .That is why i am asking?

Correct - file "mf_classic_dict_user.nfc" is missing, and it was not created during factory reset/update/reinstall. 



> Reproduced this issue, will be fixed soon

Thanks a lot! <3

**Comment by FearnessBG** [comment] 2023-12-04 11:39
Can you open it on the FZ with the browser to read it?

Which file u mean? Browser - just in "Saved" submenu?
Yes, sorry, i was asking on the Flipper in the browser can you open it from there, but then came the answer Reproduced this issue, will be fixed soon , so that is good. Was trying to help.

**Comment by Tomi2965** [comment] 2023-12-04 11:46
> Can you open it on the FZ with the browser to read it?
> 
> Which file u mean? Browser - just in "Saved" submenu? Yes, sorry, i was asking on the Flipper in the browser can you open it from there, but then came the answer Reproduced this issue, will be fixed soon , so that is good. **Was trying to help.**

Many thanks for try. Any help is always better :)

**Comment by gornekich** [comment] 2023-12-05 14:03
@Tomi2965 , we fix this issue in #3264. Please, test in on latest RC or dev and let me know if you still have any problems.

**Comment by Tomi2965** [comment] 2023-12-05 18:07
@gornekich , verified via RC 0.96.1 - it **works**. Thanks for help.

**Closed as completed** 2023-12-05 18:16 UTC
Labels: NFC
