### ISSUE TITLE
Cannot exit the infrared application

### ISSUE THREAD

**Issue by alexsuslin** [flipperdevices/flipperzero-firmware#1542] opened 2022-08-04 19:57 UTC
### Describe the bug.

Whenever press back button, the flipper just show the screen "Saved!" and nothing happened

### Reproduction

1. Add infrared as fav app
2. press down and select remote control
3. press + sign
4. create new button
5. press "back" button - saved message is shown

no way to go to home menu (just restart flipper)

### Target

FW: unknown [03-08-2022] [!] 93a4b9c4 [1323] 1.13.3.L [7] dev

### Anything else?

HW Version Info:
12.F7BC9C6 R01

**Comment by bbock** [comment] 2022-08-05 07:04
duplicate of #1536

**Comment by gsurkov** [comment] 2022-08-05 08:38
Yes.
Fix pending in #1538

**Closed as completed by gsurkov** 2022-08-05 08:38 UTC
Labels: Bug
