### ISSUE TITLE
LFRFID: 125khz "Hitag 2" / Aritech ATS1477

### ISSUE THREAD

**Issue by justindekeizer** [flipperdevices/flipperzero-firmware#3805] opened 2024-07-24 14:15 UTC
### Description of the feature you're suggesting.

One of our sites uses a 125khz tag system that the Flipper can't read and/or emulate. The tags are ATS1477 type "Aritech" and sometimes labeled as Hitag 2.

Raw tag data in the attachment. 

Anyone has any solution for this?

[RAW_TAG.zip](https://github.com/user-attachments/files/16363378/RAW_TAG.zip)

**Comment by hedger** [comment] 2024-07-30 10:38
Duplicate of #1534

**Closed as not planned by hedger** 2024-07-30 10:38 UTC
