### ISSUE TITLE
Add the possibility to set up a custom text on locked devices

### ISSUE THREAD

**Issue by auino** [flipperdevices/flipperzero-firmware#2364] opened 2023-02-06 09:07 UTC
### Description of the feature you're suggesting.

I'd like to have the possibility to set up a custom text to show when the device is locked.
For instance, it may be useful to display contact information, in case the device is lost.

**Comment by skotopes** [comment] 2023-02-10 06:46
I'll raise this topic internally to our UI/UX team.
And as for now leaving text file on SD Card with contacts will be easiest option.

**Comment by skotopes** [comment] 2023-02-10 09:27
Also duplicate of #2243

**Closed as completed by skotopes** 2023-02-10 09:27 UTC
Labels: Feature Request, UI
