### ISSUE TITLE
EM4100 RFID issue: Emulation does not work

### ISSUE THREAD

**Issue by swittenberger** [flipperdevices/flipperzero-firmware#1500] opened 2022-07-30 17:10 UTC
### Describe the bug.

Hello, I've had 3 different EM4100 tags that I could copy without any issues, but when emulating the tag, the reader doesn't detect anything. 

I've been told on discord that a reboot might help, but it didn't. What other info can I give? 
![image](https://user-images.githubusercontent.com/28090775/181934321-af5e2f9a-4603-470c-9085-f62bb9f87a4a.png)

### Reproduction

1. Read EM4100 tag
2. Emulate EM4100 tag
3. Try to open the door with flipper
4. Notice it doesn't work.

**Comment by bettse** [comment] 2022-07-30 17:12
I don't have first hand experience, but I've seen at least 3 other people with the same problem

**Comment by Astrrra** [comment] 2022-07-31 05:12
I haven't been able to replicate this issue.

https://drive.google.com/file/d/1fyJLHXRghv-VP-zwfWvneXZ-uCqj5pWQ/view?usp=drivesdk

As I asked in the reddit thread, can you please attach a video of you trying to emulate the card? This sounds like you may be doing something wrong.

**Comment by swittenberger** [comment] 2022-07-31 08:14
Hi, here is a video of the flipper not being able to emulate the RFID tag. https://drive.google.com/file/d/1clRwR54LT4bUGVUxHWEE8aykKtJO0XuV/view?usp=sharing

I will also check with a 2nd flipper as you did above, but that is a totally different case.

**Comment by Bertus-W** [comment] 2022-07-31 09:14
I can successfully use the EM4100 emulation on this product: 
https://www.surepetcare.com/en-gb/pet-doors/microchip-cat-flap-connect

I'm using the dev branch

Although I must say that the detection loop is around the entire door. and probably very strong since the small pet chip implants need to be detected.

**Comment by Kritkatten** [comment] 2022-07-31 12:27
Filmed the process as requested: [link to onedrivre](https://drive.google.com/file/d/1Rsca-HAfT6DrBxRyXwSf_PAS5yOF4d2z/view?usp=drivesdk)
I've tried rebooting the device + trying the dev version. Same result.

**Comment by swittenberger** [comment] 2022-07-31 15:17
A small update:

I've got my hands on another Flipper and was able to read from the flipper. (One emulates, the other reads) This works. 
I've tested emulation with beta firmware as well (just in case) and I could still reproduce the issue. 

The manufacturer in my case is electra.ro 
https://electra.ro/ro/produse/videointerfoane-si-interfoane/gama-pass-digital/p4s-a91i

**Comment by WhiteThePanda** [comment] 2022-07-31 17:45
Hello, my issue is pretty straightforward : 
Emulation of my tag works for the front door of the building, mailbox and other doors it is supposed to open (systematically):
https://user-images.githubusercontent.com/61516945/182038788-6b4f807d-abf3-420f-8743-67f710db17f9.mp4

and doesn't work for the door of my own appartment(systematically):
https://user-images.githubusercontent.com/61516945/182038791-9f130302-9a54-4a26-adee-ca7a54a4d012.mp4

The same key is supposed to open both.
I also tried removing the silicon case.

**Comment by DrZlo13** [comment] 2022-08-01 06:14
OK, this may be some kind of emulator protection method, or a hardware problem with concrete reader.
I will return to this topic when I finish rewriting LF-RFID core.

**Comment by swittenberger** [comment] 2022-08-01 09:53
Another update:
I've tested another tag, on another reader of different make and it works without issues. I do think it might be a security thing then on the electra one.

**Comment by 0x77dev** [comment] 2022-08-02 15:36
Hey there!

I'm trying to read tag A and write it to tag B
But it only works when I try to write dumped tag A to tag A and tab B to B
and not tag A to B or B to A

Tag A and B are EM4100

[Here is a video](https://www.youtube.com/watch?v=RGgOR_UNZNM)

**Comment by trupus** [comment] 2022-08-31 17:02
Hey guys, I had also troubles emulating the tag on an electra reader.

> The manufacturer in my case is electra.ro https://electra.ro/ro/produse/videointerfoane-si-interfoane/gama-pass-digital/p4s-a91i

Not sure if it's the exact same model as in this link, but it looks very similar to mine.

I also captured the [RAW RFID data](https://drive.google.com/drive/folders/1WnuFCMMm8dlRy8bc0wrMr3jZOFenb48e?usp=sharing). Hope it helps.

**Comment by skotopes** [comment] 2022-09-06 17:35
Please check latest release and reopen issue if problem persist.

**Comment by swittenberger** [comment] 2022-09-06 18:46
@skotopes I just tested on Dev build d1c79a83. I also tested on the stable release 0.66.1. Door still won't open. 
I have reread the rfid just in case for this test, have not used the saved one (though I did try that as well)

https://drive.google.com/file/d/1l_reeBhEbq9uMtiGM9a-h2UJR6l6ayJF/view?usp=sharing

**Comment by trupus** [comment] 2022-09-06 19:19
I had also the same problem with the latest rc today. But with a different reader this time (Flipper identified it as an EM4100 tag as well). Will try tomorrow again with the stable release.

Maybe also worth mentioning, my office has 2 doors, which you can open with the same key. It's a coworking space. The first door is "shared", but the second one can only be opened with my key. I can open the first door (and any "shared" reader in the office) with the Flipper, but the second reader is just refusing to accept the emulated key with the flipper.

**Comment by DrZlo13** [comment] 2022-09-07 00:35
OK, it's time to return to this topic. I will try to reset the protocol encoder if field is gone for ?? (10?) clocks.
Also, it will help if someone points out the problematic reader model.

**Comment by Kritkatten** [comment] 2022-09-07 05:21
Still doesn't work. I saw new data with the last update though. Picture:
![20220907_072011](https://user-images.githubusercontent.com/15158565/188794986-3e0c65d1-1d67-445e-8216-bde1414523c8.jpg)

**Comment by trupus** [comment] 2022-09-07 08:05
**EDIT:**
Oh, interesting. The key fob works on 2 frequencies. The RFID is for the main (shared) entrance, and then it also has NFC, which opens the second door. The NFC is a Mifare classic, which I was able to read and emulate. 

Sorry, but this reader is then unrelated to the described issue!

***

> Also, it will help if someone points out the problematic reader model.

At this moment I encountered 2 different readers in 2 different countries that share the described problem. I found the manufacturer for one of them: [official page](https://www.primion.de/en/products/access-control-systems/electronic-locks-and-cylinders/pkt-door-handle/), [datasheet](https://www.primion.de/fileadmin/media/Downloads/EN_Data_sheets/pKT_Door_handle_en.pdf)

**Comment by swittenberger** [comment] 2022-09-07 10:34
@DrZlo13 The reader described in this bug is an Electra, as can be found in the link above. What other information would you require?

**Comment by Montecri** [comment] 2022-09-14 18:23
Got the same issue with a different brand of reader. In my case, I even tried proxmark3 cloning to a blank key (besides flipper emulation) and the reader didn't detect. Read somewhere that some readers will try to detect if the key is writable and deny access.

**Comment by d3xt3r01** [comment] 2022-11-27 17:46
I can confirm the electra keyfob (https://electra.ro/ro/produse/videointerfoane-si-interfoane/gama-touch-line/rezidential/terminale-1/tag-elt-000)  issue. Same here using the latest firmware. Altough not the same reader. The builsing has https://electra.ro/ro/produse/videointerfoane-si-interfoane/gama-touch-line/rezidential/terminale-1/vpm-bsr02-elb this reader.

**Comment by LowSkillDeveloper** [comment] 2022-12-13 16:15
I have a "mizip" key for a coffee machine. When I try to read it, this is what I get. 

![IMG_20221213_170751_623](https://user-images.githubusercontent.com/25121341/207385063-0d636dab-4c13-4c84-9f73-e9f5c712c1c6.png)

I don't know if this information is correct or not.  Perhaps the key does not have its own id. And inside the key there is other information. After all, this key has a balance that is displayed when taking coffee.

**Comment by Ferferite** [comment] 2023-01-13 17:19
Any update on the Electra readers? Could try sniffing with a proxmark3 if that provides any useful info

**Comment by Ferferite** [comment] 2023-01-14 01:56
After a bit more digging I found some stuff. First, electra.ro is associated with electra-automation.at and they developed their own rfid solution "for maximum security". And according to [this thread](https://forum.flipperzero.one/t/electra-intercom/6368/14), [this ](https://www.nxp.com/docs/en/data-sheet/HTSICH56_48_SDS.pdf)should be the datasheet for the readers. 

just compiled some info I could find online, didn't have more time to look into it yet

**Comment by R1DEN** [comment] 2023-06-26 10:34
@DrZlo13 hey there, it seems like a working PoC is already there https://forum.flipperzero.one/t/electra-intercom/6368/65
however it would probably be better to add another protocol to the list.
If you could point to some contribution guide for such issues, I could probably open some kind of a PR, however my C skills are really rusty...

**Comment by R1DEN** [comment] 2023-09-30 22:19
@DrZlo13 any chance we could see this in the firmware any time soon?
Feels like the issue is somewhat researched and the solution is a couple of steps away for experienced contributors. :pray:

**Comment by skotopes** [comment] 2023-10-12 21:17
@R1DEN more like everyone is busy with other tasks. We'll come back eventually to this one.

**Comment by R1DEN** [comment] 2023-10-13 05:20
@skotopes thank you for the reply. Just hoping it will be sooner rather than later as this will really help for Romanian and Moldovan users, we have these intercoms almost everywhere in new apartment blocks.

**Comment by dontbug** [comment] 2023-10-13 07:31
We are waiting, we are really waiting. Thank you in advance

**Comment by gherman22** [comment] 2023-12-21 10:01
Any luck to emulating the tag on an electra reader for anyone?

**Comment by R1DEN** [comment] 2023-12-21 10:03
@gherman22 only with that "hacky" way from one of my above posts. Hope a proper way will be incorporated in the firmware some day...

**Comment by gherman22** [comment] 2023-12-21 10:53
Thank you for your answer, i tried to fallow the steps but i got lost. Mabe we will have a easier way or a video with the steps.

**Comment by skotopes** [comment] 2024-01-03 11:51
@DrZlo13 ping

**Comment by dontbug** [comment] 2024-01-03 16:10
@DrZlo13 ping

**Comment by skotopes** [comment] 2024-05-22 11:44
#3640 brought support for electra, please check latest RC or Dev and reopen if issues persist

**Closed as completed by skotopes** 2024-05-22 11:44 UTC
Labels: RFID 125kHz, Bug

**Comment by d3xt3r01** [comment] 2024-05-22 12:29
Can confirm it works!

**Comment by itrack** [comment] 2024-06-20 10:55
Should this function work?

**Comment by d3xt3r01** [comment] 2024-06-20 10:56
Yes. Works, tested.

**Comment by itrack** [comment] 2024-06-20 11:10
I managed to emulate, it works fine but when I tried to write a blank tag it didn't work:

![Screenshot-20240620-140707](https://github.com/flipperdevices/flipperzero-firmware/assets/2368391/da8444a1-1a30-432e-a6ce-18c91aa67c66)

I mention that this only when I want to write previously saved Electra tags, with other RFID tags it works ok

**Comment by itrack** [comment] 2024-06-20 11:32
it's a bit strange, if I read a tag and write over the same tag it works, if I want to write it on a different one it doesn't work

**Comment by bettse** [comment] 2024-06-20 14:53
> I tried to write a blank tag

t5577? (https://docs.flipper.net/rfid/write-data)

> write over the same tag it works

Generally not a valid test, even for a read-only tag it would appear to be successful because the tag has the same data.

**Comment by itrack** [comment] 2024-06-20 14:57
t5577 and Electra blank tag, on t5577 I managed to write other tags that are not of the Electra type

**Comment by itrack** [comment] 2024-06-20 15:09
Short demo: https://www.youtube.com/shorts/fI8o7a28TzE

Electra marks electra tags as "programmable":
![Screenshot 2024-06-20 at 18 21 16](https://github.com/flipperdevices/flipperzero-firmware/assets/2368391/b95f8f88-d276-4b57-8050-2944c2b1932b)

**Comment by skotopes** [comment] 2024-06-20 17:17
@itrack do I understand right that writing to 5577 fails too? If yes then have you tried to read this 5577 with proxmark?
Some protocols got additional payload validation and may alter data written to 5577 which may cause write fail. May be that is your case?

As of electra blank keyfobs, do you know what exactly is in the keyfob? Do they also use 5577?

**Comment by VladFlorinIlie** [comment] 2024-06-20 17:30
Why do you even bother to write an Electra tag? They are more expanse and harder to come by. As for T5577, I have tested writing them and they are recognized by the reader. I would say that reading an Electra tag and then writing the data on a T5577 should be your best bet on getting a proper tag.

**Comment by itrack** [comment] 2024-06-20 17:38
Hi @VladFlorinIlie ,

I put here a demo in which I try read electra tag and to write to T5577 and another an electra tag:
https://www.youtube.com/shorts/fI8o7a28TzE

It doesn't work.

After to prove that it is a programmable T5577 tag, I selected a previously saved tag (which was not electra), it could be written without problems.


@skotopes , it only fails when I try to write using a previously scanned electra tag, if I try any other type of rfid it works

**Comment by VladFlorinIlie** [comment] 2024-06-20 18:09
I have replicated your experiment here:
https://streamable.com/4a07vk

You can also try with the e-locks T5577 that I have used in the video. You can buy them from EMAG here:
https://www.emag.ro/set-10-bucati-tag-de-proximitate-rfid-e-locks-125-khz-chip-t5577-rewritable-galben-t5577elck/pd/D5RK86MBM/

**Comment by itrack** [comment] 2024-06-20 18:15
Bought, I'll come back with a feedback in 6 days when the products arrive :)

My tests so far have been done with:
https://www.aliexpress.com/item/1005005863796435.html?spm=a2g0o.order_list.order_list_main.11.1e331802lOqgr3
and
https://www.a2t.ro/interfoane-videointerfoane/cartela-interfon-electra.html

**Comment by itrack** [comment] 2024-06-22 10:28
Recommended tags arrived faster, same problem, thinking it is a firmware version problem, I reinstalled the original firmware:

![Screenshot 2024-06-22 at 13 12 32](https://github.com/flipperdevices/flipperzero-firmware/assets/2368391/c73ed356-bad8-4953-b55b-122d90f9e03f)

Demo video:
https://www.youtube.com/watch?v=AbJDa9PVRl4

Something's different than what you have @VladFlorinIlie , are you using custom firmware?

**Comment by itrack** [comment] 2024-06-22 10:37
I tried the following cases:

- Read original Electra Tag -> Write original Electra Tag = failed
- Read original Electra Tag -> Write china T5577 = failed
- Read original Electra Tag -> Write e-locks T5577 = failed
- Read e-locks T5577 with Electra Tag clone (written on tag) -> Write china T5577 = failed
- Read e-locks T5577 with Electra Tag clone (written on tag) -> Write another e-locks T5577 = failed
- Read random RFID (non Electra) -> Write e-locks T5577 = success
- Read random RFID (non Electra) -> Write china T5577 = success
- Read random RFID (non Electra) -> Write original Electra Tag = failed

**Comment by VladFlorinIlie** [comment] 2024-06-22 10:48
I do indeed use a custom firmware, Momentum version 004 to be exact. As far as I am aware, there shouldn't be any differences between the original firmware and this custom one when it comes to the Electra RFID protocol.
I guess trying this firmware as well wouldn't hurt :)

**Comment by itrack** [comment] 2024-06-22 11:32
I also installed Momentum v 004 , same result :)
Using the same tags as @VladFlorinIlie , but with a different result, very strange.

Any idea what could be the cause?
Could it be a hardware difference? A debug idea?

**Comment by dontbug** [comment] 2024-06-24 09:59
I have the same problem of not being able to register on the electra chips, but i could on the T5577 chips that i ordered from aliexpress. There were times when i couldn't write from the ordered ones, but it's quite possible that they are not the T5577 model specified by the seller, and i made a refund.

**Comment by itrack** [comment] 2024-06-24 10:15
@dontbug In my case, I can write anything else on T5577 tags. I write other access keys, it went without any problems.
When I try to write Electra on T5577 it does not work.
I tried 4 different types of T5577 tags, same result.

**Comment by skotopes** [comment] 2024-06-24 10:52
@itrack have you tried to read 5577 after write fail?

**Comment by itrack** [comment] 2024-06-24 11:18
@skotopes Yes,  the tag does not change

**Comment by skotopes** [comment] 2024-06-24 12:17
> @skotopes Yes, the tag does not change

interesting, could mean that formed payload is incorrect and can not be written to the card. Can you share key?

**Comment by itrack** [comment] 2024-06-24 13:20
Sure:
[electra.zip](https://github.com/user-attachments/files/15956293/electra.zip)

**Comment by itrack** [comment] 2024-06-24 13:24
btw. emulating this tag works

**Comment by skotopes** [comment] 2024-06-24 13:28
> Sure: [electra.zip](https://github.com/user-attachments/files/15956293/electra.zip)

All works:
- Parsing payload
- Emulation
- Writing to 5577
- Reading 5577

**Comment by itrack** [comment] 2024-06-24 13:33
Interesting that writing works for you, how could this be debugged?
I can't explain, I would have thought it was a problem with the RFID module if I couldn't write other cards, but it works, just in this specific case it doesn't.

Are there several hardware versions?

**Comment by skotopes** [comment] 2024-06-24 13:41
> Interesting that writing works for you, how could this be debugged? I can't explain, I would have thought it was a problem with the RFID module if I couldn't write other cards, but it works, just in this specific case it doesn't.
> 
> Are there several hardware versions?

Not in terms of RFID. Also if you can write other types you should be able to write this one too.

**Comment by itrack** [comment] 2024-06-24 14:09
I made another video testing several cases: 

- Trying to write an electra tag (failed)
- Trying to write another tag (successful)
On tags where an electra tag failed, another tag succeeded.

What could be the explanation?

https://www.youtube.com/watch?v=mKwfsRf2ZaI

**Comment by skotopes** [comment] 2024-06-24 14:11
@itrack we don't provide support for 3rd party firmware. If you use it then address all issues to appropriate firmware developers.

**Comment by itrack** [comment] 2024-06-24 14:14
here is a video with the official firmware, it is the same result:
https://www.youtube.com/watch?v=AbJDa9PVRl4

**Comment by itrack** [comment] 2024-06-24 14:33
I put back the original firmware, I did another test and discovered something a little strange.
On one type of tag although it gives error it writes part of the original tag. Nothing has been written on the other two tags types.

Original tag:
![Screenshot-20240624-172749](https://github.com/flipperdevices/flipperzero-firmware/assets/2368391/8a826f93-5286-4d15-9f1f-b838587cc592)

Clone tag:
![Screenshot-20240624-172724](https://github.com/flipperdevices/flipperzero-firmware/assets/2368391/eb0ba694-5962-41ca-af00-050002e167f3)

**Comment by eblis** [comment] 2024-10-28 13:31
I have the same problem, I could write other tags but not Electra. For Electra it writes the hex, but refuses to write the Epilogue, epilogue remains 0x000000...

**Comment by eblis** [comment] 2024-10-30 12:55
I've tried to debug the writing process but couldn't get it to work so I resorted to _print debugging_ it to try and find out some things.

After playing around with the logs I found out the following:
I added some logs to the encoder_start function:
```c++
bool protocol_electra_encoder_start(ProtocolElectra* proto) {
    // header
    proto->encoded_base_data = 0b111111111;

    // data
    for(uint8_t i = 0; i < ELECTRA_DECODED_BASE_DATA_SIZE; i++) {
        em_write_nibble(false, proto->data[i], &proto->encoded_base_data);
        em_write_nibble(true, proto->data[i], &proto->encoded_base_data);
    }

    for(int x = 0; x < 8; x++) {
        FURI_LOG_I(TAG, "Protocol data[%d] = %x", x, proto->data[x]);
    }

    // column parity and stop bit
    uint8_t parity_sum;

    for(uint8_t c = 0; c < EM_COLUMN_COUNT; c++) {
        parity_sum = 0;
        for(uint8_t i = 1; i <= EM_ROW_COUNT; i++) {
            uint8_t parity_bit = (proto->encoded_base_data >> (i * EM_BITS_PER_ROW_COUNT - 1)) & 1;
            parity_sum += parity_bit;
        }
        proto->encoded_base_data = (proto->encoded_base_data << 1) | ((parity_sum % 2) & 1);
    }

    // stop bit
    proto->encoded_base_data = (proto->encoded_base_data << 1) | 0;

    proto->encoded_data_index = 0;
    proto->encoded_polarity = true;

    // epilogue
    proto->encoded_epilogue = (proto->data[ELECTRA_DECODED_DATA_EPILOGUE_START_POS]);
    proto->encoded_epilogue <<= 8;
    proto->encoded_epilogue |= (proto->data[ELECTRA_DECODED_DATA_EPILOGUE_START_POS + 1]);

    FURI_LOG_I(TAG, "Initial encoded epilogue %llx", proto->encoded_epilogue);

    //fill bytes 2-7 by epilogue filler
    for(uint8_t i = 2; i < ELECTRA_ENCODED_EPILOGUE_SIZE; i++) {
        proto->encoded_epilogue <<= 8;
        proto->encoded_epilogue |= proto->data[ELECTRA_DECODED_DATA_EPILOGUE_START_POS + 2];
    }

    FURI_LOG_I(TAG, "Base data %llx", proto->encoded_base_data);
    FURI_LOG_I(TAG, "Encoded epilogue %llx", proto->encoded_epilogue);

    return true;
}
```
The logs show the following:
```text
32946 [I][ELECTRA] Protocol data[0] = 3
32948 [I][ELECTRA] Protocol data[1] = e8
32950 [I][ELECTRA] Protocol data[2] = 89
32952 [I][ELECTRA] Protocol data[3] = 48
32955 [I][ELECTRA] Protocol data[4] = fc
32957 [I][ELECTRA] Protocol data[5] = 7e
32959 [I][ELECTRA] Protocol data[6] = 1e
32962 [I][ELECTRA] Protocol data[7] = 0
32964 [I][ELECTRA] Initial encoded epilogue 7e1e
32967 [I][ELECTRA] Base data ff80dd8c6498fb16
32969 [I][ELECTRA] Encoded epilogue 7e1e000000000000
```
So the tag and epilogue was correctly determined.

I also added some logs to the *electra_decode* function
```c++
static void electra_decode(
    const uint8_t* encoded_base_data,
    const uint8_t encoded_base_data_size,
    const uint8_t* encoded_epilogue,
    const uint8_t encoded_epilogue_size,
    uint8_t* decoded_data,
    const uint8_t decoded_data_size) {
    furi_check(decoded_data_size >= ELECTRA_DECODED_DATA_SIZE);
    furi_check(encoded_base_data_size >= ELECTRA_ENCODED_BASE_DATA_SIZE);
    furi_check(encoded_epilogue_size >= ELECTRA_ENCODED_EPILOGUE_SIZE);

    for(int x = 0; x < encoded_epilogue_size; x++) {
        FURI_LOG_D(TAG, "Epilogue[%d] = %08x", x, encoded_epilogue[x]);
    }

    uint8_t decoded_data_index = 0;
    ElectraDecodedData base_data = *((ElectraDecodedData*)(encoded_base_data));
    // ElectraDecodedData epilogue = *((ElectraDecodedData*)(encoded_epilogue));

    FURI_LOG_T(TAG, "Decoded data size %d", decoded_data_size);
    // clean result
    memset(decoded_data, 0, decoded_data_size);

    // header
    for(uint8_t i = 0; i < 9; i++) {
        base_data = base_data << 1;
    }

    // nibbles
    uint8_t value = 0;
    for(uint8_t r = 0; r < EM_ROW_COUNT; r++) {
        uint8_t nibble = 0;
        for(uint8_t i = 0; i < 5; i++) {
            if(i < 4) nibble = (nibble << 1) | (base_data & (1LLU << 63) ? 1 : 0);
            base_data = base_data << 1;
        }
        value = (value << 4) | nibble;
        if(r % 2) {
            decoded_data[decoded_data_index] |= value;
            decoded_data_index++;
            value = 0;
        }
    }
    for(int x = 0; x < decoded_data_size; x++) {
        FURI_LOG_I(TAG, "Initial data[%d] = %08x", x, decoded_data[x]);
    }

    // copy first 3 bytes of encoded epilogue to decoded data
    FURI_LOG_D(
        TAG,
        "ELECTRA_ENCODED_EPILOGUE_SIZE %d VS encoded_epilogue_size %d",
        ELECTRA_ENCODED_EPILOGUE_SIZE,
        encoded_epilogue_size);
    decoded_data[ELECTRA_DECODED_DATA_EPILOGUE_START_POS] =
        encoded_epilogue[encoded_epilogue_size - 1];
    decoded_data[ELECTRA_DECODED_DATA_EPILOGUE_START_POS + 1] =
        encoded_epilogue[encoded_epilogue_size - 2];
    decoded_data[ELECTRA_DECODED_DATA_EPILOGUE_START_POS + 2] =
        encoded_epilogue[encoded_epilogue_size - 3];

    for(int x = 0; x < decoded_data_size; x++) {
        FURI_LOG_W(TAG, "Final Data[%d] = %08x", x, decoded_data[x]);
    }
}
```

This is the log
```text
32972 [D][ELECTRA] Epilogue[0] = 00000000
32974 [D][ELECTRA] Epilogue[1] = 00000000
32977 [D][ELECTRA] Epilogue[2] = 00000000
32979 [D][ELECTRA] Epilogue[3] = 00000000
32981 [D][ELECTRA] Epilogue[4] = 00000000
32984 [D][ELECTRA] Epilogue[5] = 00000000
32986 [D][ELECTRA] Epilogue[6] = 0000001e
32988 [D][ELECTRA] Epilogue[7] = 0000007e
32991 [T][ELECTRA] Decoded data size 8
32993 [I][ELECTRA] Initial data[0] = 00000003
32995 [I][ELECTRA] Initial data[1] = 000000e8
32998 [I][ELECTRA] Initial data[2] = 00000089
33000 [I][ELECTRA] Initial data[3] = 00000048
33003 [I][ELECTRA] Initial data[4] = 000000fc
33005 [I][ELECTRA] Initial data[5] = 00000000
33008 [I][ELECTRA] Initial data[6] = 00000000
33011 [I][ELECTRA] Initial data[7] = 00000000
33013 [D][ELECTRA] ELECTRA_ENCODED_EPILOGUE_SIZE 8 VS encoded_epilogue_size 8
33017 [W][ELECTRA] Final Data[0] = 00000003
33019 [W][ELECTRA] Final Data[1] = 000000e8
33022 [W][ELECTRA] Final Data[2] = 00000089
33024 [W][ELECTRA] Final Data[3] = 00000048
33027 [W][ELECTRA] Final Data[4] = 000000fc
33029 [W][ELECTRA] Final Data[5] = 0000007e
33032 [W][ELECTRA] Final Data[6] = 0000001e
33034 [W][ELECTRA] Final Data[7] = 00000000
```

Then after a while it writes the T5577 blocks, as such:
```
33115 [D][LfRfidWorker] Data write
33117 [D][T5577] About to write 5 blocks
33117 [D][T5577] Writing data block 148080
33117 [D][T5577] Writing data block ff80dd8c
33117 [D][T5577] Writing data block 6498fb16
33117 [D][T5577] Writing data block 7e1e0000
33117 [D][T5577] Writing data block 0
33117 [D][T5577] Finished writing 5 blocks
```
One question here, shouldn't block 4 (the epilogue) use the same Manchester encoding as the first 3 blocks ?

Then flipper I assume reads what was written and it reads everything, except the epilogue, which remains 00 00 00 ...
```text
33118 [D][LfRfidWorker] Start ASK
33580 [D][LfRfidWorker] Read started
34646 [E][ELECTRA] Parity bit is wrong
34648 [E][ELECTRA] Parity bit is wrong
34650 [E][ELECTRA] Parity bit is wrong
34654 [E][ELECTRA] Parity bit is wrong
34657 [E][ELECTRA] Parity bit is wrong
34659 [E][ELECTRA] Parity bit is wrong
34661 [E][ELECTRA] Parity bit is wrong
34664 [E][ELECTRA] Parity bit is wrong
34667 [D][ELECTRA] Epilogue[0] = 00000000
34669 [D][ELECTRA] Epilogue[1] = 00000000
34671 [D][ELECTRA] Epilogue[2] = 00000000
34673 [D][ELECTRA] Epilogue[3] = 00000000
34676 [D][ELECTRA] Epilogue[4] = 00000000
34678 [D][ELECTRA] Epilogue[5] = 00000000
34681 [D][ELECTRA] Epilogue[6] = 00000000
34683 [D][ELECTRA] Epilogue[7] = 00000000
34685 [T][ELECTRA] Decoded data size 8
34687 [I][ELECTRA] Initial data[0] = 00000003
34690 [I][ELECTRA] Initial data[1] = 000000e8
34692 [I][ELECTRA] Initial data[2] = 00000089
34695 [I][ELECTRA] Initial data[3] = 00000048
34697 [I][ELECTRA] Initial data[4] = 000000fc
34700 [I][ELECTRA] Initial data[5] = 00000000
34703 [I][ELECTRA] Initial data[6] = 00000000
34705 [I][ELECTRA] Initial data[7] = 00000000
34708 [D][ELECTRA] ELECTRA_ENCODED_EPILOGUE_SIZE 8 VS encoded_epilogue_size 8
34711 [W][ELECTRA] Final Data[0] = 00000003
34714 [W][ELECTRA] Final Data[1] = 000000e8
34716 [W][ELECTRA] Final Data[2] = 00000089
34719 [W][ELECTRA] Final Data[3] = 00000048
34721 [W][ELECTRA] Final Data[4] = 000000fc
34724 [W][ELECTRA] Final Data[5] = 00000000
34726 [W][ELECTRA] Final Data[6] = 00000000
34729 [W][ELECTRA] Final Data[7] = 00000000
```

**Comment by itrack** [comment] 2024-10-30 14:32
@skotopes can you take a look?

**Comment by skotopes** [comment] 2024-12-02 06:51
@itrack can you make one more issue, @Astrrra will take a look

**Comment by eblis** [comment] 2024-12-02 07:39
I have already created another issue for Electra tags and @itrack commented there as well. Issue number is #3997

**Comment by skotopes** [comment] 2024-12-02 07:41
got it, let's continue there
