### ISSUE TITLE
PIN Resets Between Firmware Updates

### ISSUE THREAD

**Issue by lumeyisnotyou** [flipperdevices/flipperzero-firmware#2976] opened 2023-08-11 04:13 UTC
### Describe the bug.

When updating to 89-rc (and 88-rc before that), my PIN was reset mid during the upgrade.

### Reproduction

1. Set a PIN
2. Upgrade firmware
3. PIN is reset.

**Comment by doomwastaken** [comment] 2023-08-11 09:28
> Can confirm this, opened a ticket FL-3482

edit: closing the ticket, turns out it is expected behavior due to update. Will advice that there should be a message about in the release notes

**Closed as not planned** 2023-08-11 10:14 UTC
Labels: Bug, Core+Services
