### ISSUE TITLE
GPIO, UART bridge mode, high baud rates causes data loss

### ISSUE THREAD

**Issue by g3gg0** [flipperdevices/flipperzero-firmware#2304] opened 2023-01-14 20:02 UTC
### Describe the bug.

When reading data from a ESP32 based device that used 921600 baud, I basically got clean data.
At least all received characters were correct, but after some few dozen lines of startup log, the terminal didn't show any new data anymore.
(this doesn't look like a "signal edges are too distorted, the UART can not detect the bits correctly" issue)
First thinking this might be a terminal software issue, I tried switching to another terminal and realized the "missing" data arrived there when I rebooted the target.

Here a video where i 
 - start up the ESP32 based device
 - see "half" of the log
 - unpower the device
 - start PuTTY
 - power the device (causing new data to arrive)
 - suddenly see part of the missing data

https://cdn.discordapp.com/attachments/954430078882816021/1062478654183055420/hterm_2023-01-10_22-05-47.mp4

here another video where i
 - plug in the ESP32 based device
 - see "half" of the log
 - unplug the device
 - wiggle on the RX pin of the flipper to cause some data to arrive
 - suddenly parts of the missing data arrives

https://cdn.discordapp.com/attachments/954430078882816021/1062480901033971833/hterm_2023-01-10_22-18-37.mp4

Also some content of the log is missing from now and then.
Here a captured log, done with flipper:
![grafik](https://user-images.githubusercontent.com/479231/212493284-3765ecd2-0b40-433f-a193-3d2359ea8fcf.png)

and here when captured with a standard USB/UART adapter
![grafik](https://user-images.githubusercontent.com/479231/212493316-9bb53547-3f53-4cae-bead-07c73ae8decb.png)

So I see two issues that might exist
 a) the data is arriving too fast so a small few-hundred bytes UART buffer overruns and data is lost (320 bytes correctly received as seen in the videos == USB_UART_RX_BUF_SIZE)
 b) some counter / ringbuffer pointers seem to be odd so that some data is stuck and is not immediately sent until some few single bytes arrive

### Reproduction

I am not sure if this is reproducible on your computer

here is what i've done to reproduce the issue.
 - attach an USB/UART adapter, wired up to the flippers RX/TX
 - use two terminals
 - connect one to flipper
 - connect the other to the USB/UART adapter
 - paste 1000 bytes into the terminal of the USB/UART adapter
 - no data seems to arrive until you e.g. press ENTER or some other immediately sent character a few times

Here a video:
https://user-images.githubusercontent.com/479231/212494003-a0b18008-52a5-4e40-8ebe-33001d63961c.mp4

### Target

dev 8D2143AD

**Comment by DrZlo13** [comment] 2023-01-15 16:32
Can you check if this issue is reproduced in dap link app?

**Comment by g3gg0** [comment] 2023-01-17 09:36
tried with this text:
![grafik](https://user-images.githubusercontent.com/479231/212862161-21e35fb9-2551-4d48-b013-c9ab9e408083.png)
[letter] [99 digits] [letter] [99 digits] ...

received using DAP-Link:
![grafik](https://user-images.githubusercontent.com/479231/212870188-deaad215-625e-43b7-bb28-290dc6263e9a.png)


this using GPIO app:
![grafik](https://user-images.githubusercontent.com/479231/212869973-bbc4e0fc-0a82-4ee6-884e-9ca9e68162b1.png)

**Comment by g3gg0** [comment] 2023-01-17 10:10
it seems we are talking about 320 and 512 byte block sizes for GPIO app and DAP-Link app.

**Comment by g3gg0** [comment] 2023-01-25 14:12
@DrZlo13 any updates on this?

**Comment by g3gg0** [comment] 2023-01-27 12:31
Is this information enough and do you already know where to look?
Can you reproduce this or am I missing something or doing something wrong?

**Comment by skotopes** [comment] 2023-02-10 07:46
Okay, let's make one step back: Can you test devices separately? Get good USB serial adapter and check that flipper and esp behave correctly.

**Comment by g3gg0** [comment] 2023-02-10 14:17
as written in the first post:

USB-UART Adapter + ESP32 => good
![grafik](https://user-images.githubusercontent.com/479231/218113706-c0dcc782-203e-4233-b091-58e2b0c979cd.png)

Flipper + ESP32 => bad
![grafik](https://user-images.githubusercontent.com/479231/218113897-40e14635-ad56-4af9-afde-bddd965bbb3a.png)

**Comment by g3gg0** [comment] 2023-02-13 14:15
> Okay, let's make one step back: Can you test devices separately? Get good USB serial adapter and check that flipper and esp behave correctly.

does this match what you asked for?

**Comment by skotopes** [comment] 2023-02-13 14:16
Yep, we'll take a look on it.

**Comment by g3gg0** [comment] 2023-02-13 20:42
great, thanks

**Comment by TQMatvey** [comment] 2023-03-07 04:50
i was working on an esp32 raw monitor capturing mode, and used flipper to get data, it was also corrupred, baud rate was 921600, cant provide any more details as project is dropped due to those issues...

flipper definitely has issues capturing at high baud rates, not only in uart bridge, bad uart > sdcard as well as the app for flipper was written to directly try writing from uart to internal sdcard, worked but data was corrupted on high baud rates, 115200 was working perfectly

**Comment by skotopes** [comment] 2024-07-07 14:27
@g3gg0 should have been fixed in January UART refactoring.

**Comment by skotopes** [comment] 2024-07-07 14:28
reopen if issue persist.

**Closed as completed by skotopes** 2024-07-07 14:27 UTC
Labels: USB, Bug
