### ISSUE TITLE
Cannot compile firmware on Apple Silicon

### ISSUE THREAD

**Issue by adamm** [flipperdevices/flipperzero-firmware#1230] opened 2022-05-14 03:23 UTC
Hello,

Building Flipper Firmware on MacOS using Apple Silicon fails with a super strange syntax error messages.   In my case I have a Macbook Air (M1 2020).

TLDR: There is a workaround.  Downgraded brew cask gcc-arm-embedded to version 10.3.   See below.

**To Reproduce**
1. Get an Apple M1 laptop
2. `brew bundle --verbose`
3. `make`
4. Build starts OK, but soon very strange "syntax" errors soon occur.  Build falis.

**Logs**
I'll attach the full log output, but here's a snippet.  4 or 5 other errors with seemingly basic syntax similar to the following:
```
/Users/adamm/git/flipper/unleashed/applications/power/power_service/power.c: In function 'power_check_low_battery':
/Users/adamm/git/flipper/unleashed/applications/power/power_service/power.c:155:5: internal compiler error: Illegal instruction: 4
  155 |     if((power->info.charge == 0) && (power->info.voltage_vbus < 4.0f) &&
      |     ^~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.linaro.org/> for instructions.
make[1]: *** [.obj/f7-firmware//Users/adamm/git/flipper/unleashed/applications/power/power_service/power.o] Error 1
```
Full log: 
[flipper-firmware-build-failure.log](https://github.com/flipperdevices/flipperzero-firmware/files/8692060/flipper-firmware-build-failure.log)
 

**Workaround**
Downgrade your brew installation of gcc-arm-ebedded to 10.3.
1. `cd $(brew --repo homebrew/cask)`
2. `git checkout d407663b8017a0a062c7fc0b929faf2e16abd1ff`    # version 10.3 of gcc-arm-embedded
3. `HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall gcc-arm-embedded`
4. `git checkout master`
5. `make` in flipperzero-firmware now works.

**Additional context**
Issue occurs both on dev and release branches.

**Comment by DrZlo13** [comment] 2022-05-16 12:07
Same. GCC 11 on M1 is broken.

**Comment by skotopes** [comment] 2022-05-16 13:38
We are working on new compiler toolchain. 
Meanwhile you can downgrade to 10.3 version, it should work fine.

**Comment by itizir** [comment] 2022-06-10 23:00
The problem is not exclusive to M1: basically same thing on Intel chip.
Thanks for the detailed workaround instructions!

**Comment by J3G0** [comment] 2022-07-08 13:52
Version 10.3 of GCC works

**Comment by skotopes** [comment] 2022-07-08 13:53
We almost finished fix. Will be included in next release

**Comment by hedger** [comment] 2022-07-20 20:16
@adamm please try building latest dev. It should download toolchain & everything necessary.
Reopen if you encounter any issues.

**Closed as completed by hedger** 2022-07-20 20:16 UTC
Labels: Bug

**Comment by FlorianTopf** [comment] 2022-07-20 20:47
I just checked out current dev branch (ec57dd310a6ad9657c08d143bd82a66da532dc78) build and flashed my flipper successfully with an Apple M1 Pro (2021).
