### ISSUE TITLE
Unable to exit remote menu

### ISSUE THREAD

**Issue by nicoSWD** [flipperdevices/flipperzero-firmware#1426] opened 2022-07-21 11:00 UTC
**Describe the bug**
When I go to the remote menu, and add a new one using the `+` button, I'm able to save new ones, but I'm unable to return home afterwards. Pressing the back button just displays the "saved" screen, and then returns to the remote menu.

![flipper](https://user-images.githubusercontent.com/205852/180197148-a704cdf7-623c-42b8-a842-7218a9051b38.gif)

**To Reproduce**
1. Press down form the home screen
2. Scroll to the IR menu
3. Select `+`
4. Add new remote and save it
5. Press back button

**Expected behavior**
I expect to return to the home screen

**Comment by gsurkov** [comment] 2022-08-05 09:15
Closing as duplicate of #1536 (even if this one technically got reported earlier).
Fix pending in #1538.

**Closed as completed by gsurkov** 2022-08-05 09:15 UTC
Labels: Infrared, Bug, UI
