### ISSUE TITLE
Infrared Macro/Playlist

### ISSUE THREAD

**Issue by johne8** [flipperdevices/flipperzero-firmware#1906] opened 2022-10-21 19:43 UTC
### Description of the feature you're suggesting.

Is it possible to add macro/playlist support for Infrared signals?

**Comment by skotopes** [comment] 2022-10-22 15:03
The best option will be to implement it as external application. We don't plan to do that, but someone from community may take the task.

**Comment by gsurkov** [comment] 2022-10-24 09:25
Looks like a duplicate of #1800. As said above, there are no immediate plans on implementing it, but we will welcome every community effort in that direction.

**Closed as completed by gsurkov** 2022-10-24 09:25 UTC
Labels: Feature Request, Infrared
