### ISSUE TITLE
NFC renaming issue

### ISSUE THREAD

**Issue by grugnoymeme** [flipperdevices/flipperzero-firmware#3161] opened 2023-10-19 18:41 UTC
After renaming a .nfc file in any subdirectory in nfc folder e.g. ’/ext/nfc/example_directory’, the file Is moved to the main nfc dir..

**Comment by gornekich** [comment] 2023-10-31 09:12
Hello @grugnoymeme 
I think this issue was fixed in #3050 . I can't reproduce this issue on latest RC. Soon the fix will be in Release.
Please, try to reproduce it on latest RC [0.94.1-rc](https://github.com/flipperdevices/flipperzero-firmware/releases/tag/0.94.1-rc) and let me know if the issue is still present

**Closed as completed** 2023-11-01 14:50 UTC
Labels: NFC, Bug

**Comment by grugnoymeme** [comment] 2023-11-03 20:34
@gornekich yes it is fixed! thank u!! very nice work! complimentS!!
