### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by Emzarii** [flipperdevices/flipperzero-firmware#1996] opened 2022-11-10 11:07 UTC
### Describe the bug.

After I updated software my Bluetooth connection on flipper stopped switching on bt module, so that I cannot connect to any device via bt

### Reproduction

Do not know what to write here

**Comment by LowSkillDeveloper** [comment] 2022-11-10 12:20
I have the similar problem after using "Bluetooth Remote".  After using it on the phone, the phone cannot connect to the flipper through the app. I solved by delete the pair in the bluetooth settings on phone and flipper and data reset of flipper application on phone. 

And I didn't use this tool anymore, because it happens every time after use.

**Comment by skotopes** [comment] 2022-12-01 17:46
Hi guys, we need logs from flipper and your device to reproduce and fix this issue. Also device model/OS will be nice to know.

**Comment by skotopes** [comment] 2022-12-20 14:50
There is a fix in latest dev, which also will be included in next release. Please check and reopen if your issue is still persist.

**Closed as completed by skotopes** 2022-12-20 14:50 UTC
Labels: Bug

**Comment by Davidberzerk** [comment] 2023-12-24 23:19
I have most current iOS and my flipper Bluetooth won't work since I put extreme on it I'll delete flipper and reinstall and see

**Comment by skotopes** [comment] 2023-12-24 23:53
@Davidberzerk we don't provide support for 3rd party firmware.
